---
title: "第十二章重复测量设计资料的方差分析"
author: "x2yline"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: vignette

bibliography: bibliography.bib

csl: ../css/bluebook2.csl
---

> 这一章首先介绍了重复测量资料的一些特征，然后讲解了重复测量资料的分析方法和一些注意事项

## 知识清单  {#t}
* [1. 重复测量资料的数据特征](#a0)
    * [未设立平行对照的前后测量设计](#a1)
    * [设立平行资料的前后测量设计](#a2)
    * [重复测量设计](#a3)
* [2. 重复测量数据的两因素多水平分析](#b0)
    
## 1. 重复测量资料的数据特征 {#a0}
### [1.1 未设立平行对照的前后测量设计](#t) {#a1}
> 重复测量资料（repeated measurement data）最常见情况是同一个试验对象前后有2次测量结果的试验，也称前后测量设计（premeasure-postmeasure design），**最为常见**的重复测量资料。

#### 注意与配对t区分：
* 配对t两单位**随机分配**，同期观测结果；前后测量设计不能同期观测，本质是比较处理前后差别，假定**测量时间对结果是没有影响**的
* 配对t要求观察结果与差值**独立**，差值服从**正态分布**；前后测量设计的观察结果与差值不独立，观察结果与差值**相关**
* 配对t用平均差值**推论处理的作用**；前后测量设计**除了**分析平均差值外还可进行相关**回归分析**，计算截距的p值和回归系数的p值


### [1.2 设立平行资料的前后测量设计](#t) {#a2}

> 为了排除重复测量之间的其他因素（状态的改变）的影响，需要设置处理组和对照组进行前后测量，最后再进行比较。

若处理组和对照组前后的差值满足**方差齐性**，并且其**基线相值相等**（为了保证差值可以作为判别组间差别的依据），则可以进行**成组样本t检验**，然而大多数情况下都**不满足这两个条件**，所以一般不能用这种方法进行简单分析。

### [1.3 重复测量设计](#t) {#a3}
> 当前后测量设计的重复测量次数m>=3时，称重复测量设计或重复测量数据

#### 与随机区组设计的区别

1. 重复测量设计中“处理”是在区组（受试者）间随机分配，区组内的各时间点是固定的，不能随机分配

2. 重复测量设计区组内实验单位彼此不独立

> 重复测量数据若满足“球对称”假设(sphericity)，可用随机区组方差分析；若不满足“球对称”假设，亦可用随机区组方差分析，但需校正时间效应F界值的自由度。

<!-- #### R语言实现Mauchly球对称检验 -->
<!-- 在重复测量的方差分析中，实验对象被测量多次，所以会存在组内因子，组内因子要以下面的形式特别标明出来，其中B是组间因子，W是组内因子，subject是实验对象的ID， -->
<!-- model=aov(Y ~ B * W + Error(Subject/W)) -->

## 2. 重复测量数据的两因素多水平分析 {#b0}

变异由两部分组成，一是各对象的个体差异（$SS_{组间}$），二是每个对象的前后测量差异（$SS_{组内}$）。

> 各对象的个体差异继续分解为各处理分组之间的差异和误差

> 前后测量差异继续分解为前后之间的主效应差异和由处理分组与前后测量交互造成的差异，最后还有误差。

由此得到两个方差分析表：  
表一：各处理组别之间是否有差别（即分组的主效应方差分析）  
表二：测量前后之间以及不同分组的测量前后是否有交互效应的方差分析



